version: "3.8"

services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    environment:
      - WG_HOST=<dominio_dns_dinamico> # Nombre del dominio DNS Dinámico
      - PASSWORD=<password_wg> # Contraseña portal WEB WireGuard
      # Subred
      - WG_DEFAULT_ADDRESS=10.8.0.x # Subred
      - WG_DEFAULT_DNS=10.8.1.3 # IP Pihole en subred
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    volumes:
      - ./config/wireguard/etc-wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2 #IP WireGuard

  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    environment:
      - WEBPASSWORD=<password_ph> # Contraseña portal WEB Pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5353:80/tcp
    volumes:
      - ./config/pihole/etc-pihole:/etc/pihole
      - ./config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3 # IP Pihole

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
